name: staging
inputs:
    s3bucket.config.accessKey:
        secret: ENC[AES256_GCM,data:USwOlCSECS4ThlzHsIPr0xEGXXE=,iv:vU7Br/s76AuIo/omvOYUtkTzHhncNaPuOM5lLHQOQAs=,tag:CFRO47q9X8Bx6iN1B2/qWA==,type:str]
    s3bucket.config.region:
        text: us-east-1
    s3bucket.config.secretKey:
        secret: ENC[AES256_GCM,data:NWXn2Ji3yPOt2YgiQWvrQF2/nD59E6cDyKb7u3uhi0jCVjJaM8ICUw==,iv:MGPC+dmcwBdXGQd/k3t5DnYQNnw5543mwwxYlOc3d70=,tag:hiWk7Ra4s8ai8Lee1LtwWg==,type:str]
    source:
        dir:
            path: .
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1c3lKMk5SRFVQZFRCc3NC
            d2NJRmpLYzZPWmRrc3d2MHZZeEtJb2tad1hnCmxiTTJGMzJweTIrc0hhZjgybVJx
            R2E4QkxEN2ZWdnpuV043YXdmVjJkT2cKLS0tIHhmUWhBenFkVnhXd0pUNEY4L3hV
            dVVTUldnQlVNVWhydGF1Y3VxaEZqaHMKnIXHGI1Xvk7rmpqEjM5NpXJlQmUpB0H/
            GxXAIxE1suHH81PgBbUfbBV6KNpfyJb5fxq8daQIqkRyYUMsAkg+lA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-06-08T14:49:35Z"
    mac: ENC[AES256_GCM,data:Nyp0IsFCGPJEBvey3LlsD68AxOaAivU3oSKzbgg3mww6pzPAyGG6Dezbxt6w/c3+zHvmCH4B07ngXhZjyyfoYmQzm0o7VoeOcNTXPYUCJNEYfTwGO9CS21bvm9CuxM0kdOQHHIsLuqEQR7xW2uUYuP472p51urNxR2iTdTvsnms=,iv:POlSCMYCKYJXIWxWnUZdChFTW4/5weapbS5GDdHKpvc=,tag:re3kKPYg+Hnh4tTOgKOy4g==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
