apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
  labels:
    app: todoapp
spec:
  replicas: 1
  template:
    metadata:
      name: todoapp
      labels:
        app: todoapp
    spec:
      containers:
        - name: todoapp
          image: public.ecr.aws/j7f8d3t2/todoapp@sha256:6224c86267a798e98de9bfe5f98eaa3f55a1adfcd6757acc59e593f2ccdb37f2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
  selector:
    matchLabels:
      app: todoapp

